name: Run Docker image build and tag

on: workflow_dispatch

# on:
#   push:
#     tags:
#       - '*'
#     branches:
#       - master
#       - develop
#       - hotfix/*
#       - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare docker
        uses: ./.github/actions/docker
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Generate tag
        env:
          IMAGE_TAG: '${{ github.ref_name }}'
        run: echo "IMAGE_TAG=${IMAGE_TAG/\//-}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: heseya/roby-storefront:${{ env.IMAGE_TAG }}
