name: Trigger external actions
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create image tag
        env:
          IMAGE_NAME: '${{ github.ref_name }}'
        run: echo "IMAGE_NAME=${IMAGE_NAME/\//-}" >> $GITHUB_ENV
      - name: curl
        uses: enflo/curl-action@master
        with:
          curl: -X POST -F token=${{ secrets.TRIGGER_TOKEN }} -F ref=main -F variables[IMAGE_NAME]=${{ env.IMAGE_NAME }} -F variables[CI_BRANCH]=${{ github.ref_name }} ${{ vars.TRIGGER_URL }}
